### ISSUE TITLE
How do I use session meta data in computed property?

### ISSUE THREAD

**Issue by csprocket777** [simplabs/ember-cli-simple-auth-oauth2#10]
I'm returning the logged in user's model back with the authentication session. I can see how to use this in a template setting. However I'm also trying to render a navigation based on permissions in the user's model.

The privileges are just a DS.hasMany() on the user model which are embedded with the record (no async).

Here's the user model that gets returned:

```
import DS from 'ember-data';
export default DS.Model.extend({
    first_name:             DS.attr('string'),
    last_name:              DS.attr('string'),
    email_address:          DS.attr('string'),
    privileges:             DS.hasMany('privilege', {inverse: 'users'}),
    account_rep:            DS.belongsTo('user'),
    organization:           DS.belongsTo('organization', {inverse:'users', async:true}),

    full_name: function(){
        return this.get('first_name')+" "+this.get('last_name');
    }.property('first_name', 'last_name')
});
```

The navigation controller is rendered into the application.hbs with no model.
application.hbs:

```
{{render "ui/navigation"}}
{{outlet}}
```

navigation controller:

```
import Ember from 'ember';

export default Ember.ObjectController.extend({

    navItems:function(){
        return [
            Ember.Object.create({
                title:  'Accounts',
                route:  'accounts',
                privileges:[
                    '1',
                    '2'
                ]
            })
        ];
    }.property(),

    model: function(){
        return null; //unfinished
    }.property('session.user.privileges')
});
```

I can see that the navigation controller has a "session" property that has the user model and privileges I'm looking to base my navigation on, however when I setup a computed property for "session.user.privileges" I get the following error in the console:

```
TypeError: Cannot read property 'unchain' of undefined
```

![screen shot 2014-11-17 at 3 21 49 pm](https://cloud.githubusercontent.com/assets/4195745/5077913/909fa838-6e6d-11e4-8c72-8878985b9f03.png)

![screen shot 2014-11-17 at 3 24 59 pm](https://cloud.githubusercontent.com/assets/4195745/5077971/fac650c2-6e6d-11e4-86ee-abc422b64a38.png)

**Comment by NathanJang** [comment]
@csprocket777 Did you find a different approach?

**Comment by dustinfarris** [comment]
It seems like this should be an open issue.  You should be able to access async properties from the injected user in the model hook.

**Comment by dustinfarris** [comment]
You can work around like this:

```js
export default Ember.Route.extend({
  
  model: function() {
    return new Ember.RSVP.Promise(function(resolve) {
      this.get('session.user').then(function(user) {
        var paternalGrandfather = user.get('dad.dad');
        resolve(paternalGrandfather);
      });
    });
  }
});
```
